baseURL = 'https://legislatives-2022.lucie-croissant.fr/'
title = "Lucie Croissant - LÃ©gislatives 2022"
DateFormat = "02 January 2006"
theme = "lucie"
[menu]
    [[menu.main]]
    [[menu.footer]]
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true